// <auto-generated />
using System;
using LearnWeb.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnWeb.EntityFramework.Migrations
{
    [DbContext(typeof(GameManagementDbContext))]
    [Migration("20240521135257_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LearnWeb.Entites.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8b61ec8-5ba6-462c-90be-adf6d4be384f"),
                            Classes = "Mage",
                            DateCreated = new DateTime(2024, 5, 21, 21, 52, 57, 241, DateTimeKind.Local).AddTicks(4834),
                            Level = 99,
                            Nickname = "Code Man",
                            PlayerId = new Guid("c6083db3-e67c-459d-8e4a-0e62e5850066")
                        },
                        new
                        {
                            Id = new Guid("bf0e43a2-55ea-4cd3-8680-9a35da6cc6eb"),
                            Classes = "Warrior",
                            DateCreated = new DateTime(2024, 5, 21, 21, 52, 57, 241, DateTimeKind.Local).AddTicks(5058),
                            Level = 90,
                            Nickname = "Iron Man",
                            PlayerId = new Guid("c6083db3-e67c-459d-8e4a-0e62e5850066")
                        },
                        new
                        {
                            Id = new Guid("225af06c-52d0-4c28-a35d-d959f9cd9172"),
                            Classes = "Druid",
                            DateCreated = new DateTime(2024, 5, 21, 21, 52, 57, 241, DateTimeKind.Local).AddTicks(5062),
                            Level = 80,
                            Nickname = "Spider Man",
                            PlayerId = new Guid("c6083db3-e67c-459d-8e4a-0e62e5850066")
                        },
                        new
                        {
                            Id = new Guid("a99c98d2-9fa9-4106-ad99-42b9f44cb062"),
                            Classes = "Death Knight",
                            DateCreated = new DateTime(2024, 5, 21, 21, 52, 57, 241, DateTimeKind.Local).AddTicks(5065),
                            Level = 90,
                            Nickname = "Batman",
                            PlayerId = new Guid("366e7cf5-b11e-4148-9ade-3b8d60861120")
                        },
                        new
                        {
                            Id = new Guid("f15dfc25-eca5-4124-af1d-a7490930eb54"),
                            Classes = "paladin",
                            DateCreated = new DateTime(2024, 5, 21, 21, 52, 57, 241, DateTimeKind.Local).AddTicks(5067),
                            Level = 99,
                            Nickname = "Superman",
                            PlayerId = new Guid("366e7cf5-b11e-4148-9ade-3b8d60861120")
                        });
                });

            modelBuilder.Entity("LearnWeb.Entites.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6083db3-e67c-459d-8e4a-0e62e5850066"),
                            Account = "mw2021",
                            AccountType = "Free",
                            DateCreated = new DateTime(2024, 5, 21, 21, 52, 57, 241, DateTimeKind.Local).AddTicks(3425)
                        },
                        new
                        {
                            Id = new Guid("366e7cf5-b11e-4148-9ade-3b8d60861120"),
                            Account = "dc2021",
                            AccountType = "Free",
                            DateCreated = new DateTime(2024, 5, 21, 21, 52, 57, 241, DateTimeKind.Local).AddTicks(3440)
                        });
                });

            modelBuilder.Entity("LearnWeb.Entites.Character", b =>
                {
                    b.HasOne("LearnWeb.Entites.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LearnWeb.Entites.Player", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
